#! /bin/bash

path=/home/ubuntu/AngryBirds/SDCard/images/
path2=/home/ubuntu/AngryBirds/SDCard/images_old/
script=/home/ubuntu/AngryBirds/Concat/concat_test.sh

# Rename current images folder to images_old
echo $path
sudo mv ${path} ${path2}
sudo mkdir ${path}

# Concat all the image files into video clips
echo "ATTEMPTING TO CONCAT IMAGES INTO AVI ..."
find ${path2:?} -type d | while read dir; do
     echo "PROCESSING DIRECTORY: $dir"
     cd $dir
     now=$(date +"%m-%d-%Y_%H.%M.%S")
     echo "$now"
     id="/home/ubuntu/AngryBirds/SDCard/videos/$now.avi"
     echo "$id"
     sudo avconv -f image2 -r 20 -i "$dir"/%03d.jpg -b:v 1000k "$id"
     echo
done
echo "DONE"
echo

# Show me the videos have been created
echo "SHOWING CLIPS ..."
ls /home/ubuntu/AngryBirds/SDCard/videos/
echo "DONE"
echo

# Keep the videos, remove the images
echo "REMOVING IMAGES DIR AND ITS CONTENTS ..."
# rm -r /home/ubuntu/AngryBirds/SDCard/images_old/
sudo rm -r ${path2} 
echo "DONE"
